runtime: python312
entrypoint: streamlit run app.py --server.port=8080 --server.address=0.0.0.0

env: standard
instance_class: F4_1GB

env_variables:
  PYTHONUNBUFFERED: "1"
  STREAMLIT_SERVER_HEADLESS: "true"
  STREAMLIT_SERVER_PORT: "8080"
  STREAMLIT_SERVER_ADDRESS: "0.0.0.0"
